web:
  restart: always
  build: ./web/
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
    - elasticsearch:elasticsearch
  env_file: env
  volumes:
    - ./web:/data/web
  command: /usr/bin/gunicorn etsy.wsgi:application --pythonpath etsy -w 2 -b :8000 --reload

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  volumes:
    - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./backups/postgresql:/backup
  env_file:
    - env
  expose:
    - "5432"

elasticsearch:
  restart: always
  image: elasticsearch:6.4.2
  volumes_from:
    - data
  expose:
    - "9200"

redis:
  restart: always
  image: redis:latest
  expose:
    - "6379"

data:
  restart: always
  image: alpine
  volumes:
    - ./data/postgresql:/var/lib/postgresql
    - ./data/elastic:/usr/share/elasticsearch/data
  command: "true"
