# Generated by Django 2.1.1 on 2018-09-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
