# Generated by Django 2.1.1 on 2018-09-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0002_auto_20180929_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=45, null=True, verbose_name='user first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45, null=True, verbose_name='user last name'),
        ),
    ]
