# Generated by Django 2.1.1 on 2018-10-07 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0004_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(
                max_length=20, null=True, verbose_name='shop_country'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_owner',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
