# Generated by Django 2.1.1 on 2018-10-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0005_auto_20181007_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
