# Generated by Django 2.1.1 on 2018-10-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0006_auto_20181007_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='product_name')),
                ('description', models.CharField(max_length=255, verbose_name='product_description')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_core.Shop')),
            ],
        ),
    ]
