# Generated by Django 2.1.1 on 2018-10-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255, verbose_name='field_name')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('options_name', models.CharField(max_length=255, verbose_name='options_name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_core.Options')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_core.Product')),
            ],
        ),
        migrations.AddField(
            model_name='optionfield',
            name='options_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_core.Options'),
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(through='etsy_core.ProductOptions', to='etsy_core.Options'),
        ),
    ]
