# Generated by Django 2.1.1 on 2018-10-19 21:20

from django.db import migrations, models
import etsy_core.models.shop


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0009_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=etsy_core.models.shop.get_image_path),
        ),
    ]
