# Generated by Django 2.1.1 on 2018-10-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0010_options_is_default'),
        ('etsy_core', '0011_shop_shop_profile_image'),
    ]

    operations = [
    ]
