# Generated by Django 2.1.1 on 2018-10-24 12:46

from django.db import migrations, models
import django.db.models.deletion
import etsy_core.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0013_auto_20181023_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=etsy_core.models.product.get_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='etsy_core.Product')),
            ],
        ),
    ]
