# Generated by Django 2.1.3 on 2018-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0015_userfavouriteshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_shops',
            field=models.ManyToManyField(through='etsy_core.UserFavouriteShop', to='etsy_core.Shop'),
        ),
    ]
