# Generated by Django 2.1.3 on 2018-11-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0016_user_favourite_shops'),
        ('etsy_core', '0015_auto_20181111_1646'),
    ]

    operations = [
    ]
