# Generated by Django 2.1.3 on 2018-11-20 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0017_merge_20181112_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavouriteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_core.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_products',
            field=models.ManyToManyField(through='etsy_core.UserFavouriteProduct', to='etsy_core.Product'),
        ),
    ]
