# Generated by Django 2.1.3 on 2018-11-17 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0017_merge_20181112_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_core.Categories')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='productcategories',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_core.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(through='etsy_core.ProductCategories', to='etsy_core.Categories'),
        ),
    ]
