# Generated by Django 2.1.3 on 2018-11-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0018_auto_20181117_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategories',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='productcategories',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='etsy_core.Categories'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductCategories',
        ),
    ]
