# Generated by Django 2.1.3 on 2018-11-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0021_auto_20181123_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=8),
            preserve_default=False,
        ),
    ]
