# Generated by Django 2.1.3 on 2018-11-26 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0023_auto_20181124_1737'),
        ('etsy_core', '0018_auto_20181120_0014'),
    ]

    operations = [
    ]
