# Generated by Django 2.1.3 on 2018-12-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0021_auto_20181129_2252'),
        ('etsy_core', '0024_merge_20181126_0054'),
    ]

    operations = [
    ]
