# Generated by Django 2.1.3 on 2018-12-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0030_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_finished',
            field=models.BooleanField(default=False),
        ),
    ]
