# Generated by Django 2.1.4 on 2018-12-09 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0030_auto_20181209_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='etsy_core.Address'),
            preserve_default=False,
        ),
    ]
