# Generated by Django 2.1.3 on 2018-12-12 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0031_product_creation_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default=False, max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default=False, max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default=False, max_length=50, null=True, verbose_name='street_name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.IntegerField(default=False, null=True, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='zipcode'),
        ),
    ]
