# Generated by Django 2.1.3 on 2018-12-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_core', '0032_auto_20181212_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default=False, max_length=10, null=True, verbose_name='zipcode'),
        ),
    ]
